### ISSUE TITLE
License

### ISSUE THREAD

**Issue by powerjungle** [kroutsis/Lan-Notifications#2]
It will be a good idea to add a LICENSE file to the repository, but @kroutsis you have to choose which license to use since it's your repo, but if you leave it without one and continue with the project, you'll have problems in the long term.

**Comment by kroutsis** [comment]
I didn't know what a license is nor its purpose.
I am new to github and to open source in general. 
I didn't thought that someone will find my repo and check my code.
Thanks for mentioning it and sorry for the late response.

**Comment by powerjungle** [comment]
Well I just wanted to mention, but I see you've added one now, nice.
